site_name: 'test-go-3'
site_description: 'Main documentation for Backstage features and platform APIs'
repo_url: https://github.com/analect-io/test-go-3
edit_uri: edit/main/docs

plugins:
  - techdocs-core

nav:
  - Getting Started:
      - Getting Started: 'docs/index.md'
